# Generated by Django 5.1.1 on 2024-09-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='username',
        ),
    ]
