# Generated by Django 5.1.1 on 2024-09-18 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_custom_user_username'),
        ('data', '0003_resume_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='access.customer'),
        ),
    ]
