# Generated by Django 5.1.1 on 2024-09-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_resume_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
