# Generated by Django 5.1.3 on 2024-11-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('birth_date', models.DateField(default='1900-01-01')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('professional_summary', models.TextField()),
                ('company_name', models.CharField(default='', max_length=255)),
                ('position', models.CharField(default='', max_length=255)),
                ('start_date', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('end_date', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('description', models.TextField(default='')),
                ('degree', models.CharField(default='', max_length=255)),
                ('institution', models.CharField(default='', max_length=255)),
                ('start_date_education', models.DateField(default='1900-01-01')),
                ('end_date_education', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('description_education', models.TextField(default='')),
                ('skill_name', models.CharField(default='', max_length=255)),
                ('proficiency_level', models.CharField(default='', max_length=255)),
                ('language', models.CharField(default='', max_length=255)),
                ('fluency', models.CharField(default='', max_length=255)),
                ('project_name', models.CharField(default='', max_length=255)),
                ('description_project', models.TextField(default='')),
                ('technologies_used', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('institution_certification', models.CharField(default='', max_length=255)),
                ('date_obtained', models.DateField(blank=True, default='1900-01-01', null=True)),
                ('reference_name', models.CharField(default='', max_length=255)),
                ('relationship', models.CharField(default='', max_length=255)),
                ('contact_info', models.CharField(default='', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_manage', to='access.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Resume_Uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000, null=True)),
                ('file', models.FileField(upload_to='resume/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_uploaded_manage', to='access.customer')),
            ],
        ),
    ]
