# Generated by Django 5.0.7 on 2024-09-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0002_certification_education_language_project_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='email',
            new_name='resume_email',
        ),
    ]
