# Generated by Django 5.1.1 on 2024-09-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_custom_user_username'),
        ('resumes_manage', '0005_remove_resume_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='access.customer'),
        ),
    ]
