# Generated by Django 5.0.7 on 2024-09-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0006_alter_resume_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='date_obtained',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='degree',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_education',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='description_project',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='end_date_education',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='fluency',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='institution',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='institution_certification',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='language',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='proficiency_level',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='project_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='reference_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='relationship',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='start_date_education',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='resume',
            name='technologies_used',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
