# Generated by Django 5.1.1 on 2024-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0008_alter_resume_end_date_alter_resume_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_obtained',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date_education',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
