# Generated by Django 5.1.1 on 2024-09-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0009_alter_resume_date_obtained_alter_resume_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='date_obtained',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='end_date_education',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date',
            field=models.DateField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_date_education',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
