# Generated by Django 5.1.1 on 2024-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0010_alter_resume_date_obtained_alter_resume_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
