# Generated by Django 5.1.1 on 2024-09-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0011_alter_resume_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
