# Generated by Django 5.0.7 on 2024-11-06 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0012_rename_resume_email_resume_email_and_more'),
        ('resumes_manage', '0012_resume_city_resume_country_resume_date_created_and_more'),
    ]

    operations = [
    ]
