# Generated by Django 5.1.1 on 2024-11-05 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_custom_user_username'),
        ('resumes_manage', '0012_rename_resume_email_resume_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_uploaded', to='access.customer')),
            ],
        ),
    ]
