# Generated by Django 5.1.1 on 2024-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0013_resume_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_uploaded',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
