# Generated by Django 5.0.7 on 2024-11-06 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_custom_user_username'),
        ('resumes_manage', '0013_merge_20241105_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='email',
            new_name='resume_email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='surname',
        ),
        migrations.CreateModel(
            name='Resume_Uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes_uploaded', to='access.customer')),
            ],
        ),
    ]
