# Generated by Django 5.0.7 on 2024-11-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0014_rename_first_name_resume_full_name_and_more'),
        ('resumes_manage', '0014_resume_uploaded_content'),
    ]

    operations = [
    ]
