# Generated by Django 5.0.7 on 2024-11-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0015_merge_20241106_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='id_card',
        ),
        migrations.AddField(
            model_name='resume',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='resume_uploaded',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
