# Generated by Django 5.0.7 on 2024-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0016_rename_full_name_resume_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='id_card',
            field=models.CharField(default='', max_length=255),
        ),
    ]
