# Generated by Django 5.0.7 on 2024-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes_manage', '0017_resume_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_uploaded',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
