# Generated by Django 5.0.7 on 2024-11-08 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_customer_resume_uploaded_used_customer_resume_used'),
        ('resumes_manage', '0018_resume_uploaded_date_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_page', models.CharField(default='', max_length=255)),
                ('url_page', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_pages', to='access.customer')),
            ],
        ),
    ]
