# Generated by Django 5.0.7 on 2024-08-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
