# Generated by Django 5.0.7 on 2024-08-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Resume',
        ),
    ]
