# Generated by Django 5.1.3 on 2024-11-08 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('resumes_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='resume_uploaded_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_customer_uploaded', to='resumes_manage.resume_uploaded'),
        ),
        migrations.AddField(
            model_name='customer',
            name='resume_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_customer_resume', to='resumes_manage.resume'),
        ),
    ]
