# Generated by Django 5.1.1 on 2024-11-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_remove_custom_user_username'),
        ('resumes_manage', '0014_resume_uploaded_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='resume_uploaded_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_customer_uploaded', to='resumes_manage.resume_uploaded'),
        ),
        migrations.AddField(
            model_name='customer',
            name='resume_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_customer_resume', to='resumes_manage.resume'),
        ),
    ]
